/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guoqiang_androidjni_JniUtils */

#ifndef _Included_com_guoqiang_androidjni_JniUtils
#define _Included_com_guoqiang_androidjni_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guoqiang_androidjni_JniUtils_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    strFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guoqiang_androidjni_JniUtils_strFromJni
  (JNIEnv *, jclass);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doVoid
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_guoqiang_androidjni_JniUtils_doVoid
  (JNIEnv *, jobject);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doShort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_guoqiang_androidjni_JniUtils_doShort
  (JNIEnv *, jobject);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doArray
 * Signature: ([Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_guoqiang_androidjni_JniUtils_doArray
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_guoqiang_androidjni_JniUtils_doInt__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doInt
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_com_guoqiang_androidjni_JniUtils_doInt__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doInt
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_guoqiang_androidjni_JniUtils_doInt__Ljava_lang_Object_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doInt
 * Signature: (DD)I
 */
JNIEXPORT jint JNICALL Java_com_guoqiang_androidjni_JniUtils_doInt__DD
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doInt
 * Signature: (DDD)I
 */
JNIEXPORT jint JNICALL Java_com_guoqiang_androidjni_JniUtils_doInt__DDD
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doInt
 * Signature: (DFZ[C)I
 */
JNIEXPORT jint JNICALL Java_com_guoqiang_androidjni_JniUtils_doInt__DFZ_3C
  (JNIEnv *, jclass, jdouble, jfloat, jboolean, jcharArray);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doInt
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_guoqiang_androidjni_JniUtils_doInt___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doInt
 * Signature: ([I[D)I
 */
JNIEXPORT jint JNICALL Java_com_guoqiang_androidjni_JniUtils_doInt___3I_3D
  (JNIEnv *, jobject, jintArray, jdoubleArray);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doInt
 * Signature: ([I[D[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_guoqiang_androidjni_JniUtils_doInt___3I_3D_3Ljava_lang_Object_2
  (JNIEnv *, jclass, jintArray, jdoubleArray, jobjectArray);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_guoqiang_androidjni_JniUtils_doString__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doObject
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_guoqiang_androidjni_JniUtils_doObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doInterface
 * Signature: (Ljava/util/Iterator;)Ljava/util/Enumeration;
 */
JNIEXPORT jobject JNICALL Java_com_guoqiang_androidjni_JniUtils_doInterface__Ljava_util_Iterator_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doStudent
 * Signature: (Lcom/guoqiang/androidjni/Student;)Lcom/guoqiang/androidjni/Student;
 */
JNIEXPORT jobject JNICALL Java_com_guoqiang_androidjni_JniUtils_doStudent__Lcom_guoqiang_androidjni_Student_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doString
 * Signature: ([Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_guoqiang_androidjni_JniUtils_doString___3Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doObjects
 * Signature: ([Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_guoqiang_androidjni_JniUtils_doObjects
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doInterface
 * Signature: ([Ljava/util/Iterator;)[Ljava/util/Enumeration;
 */
JNIEXPORT jobjectArray JNICALL Java_com_guoqiang_androidjni_JniUtils_doInterface___3Ljava_util_Iterator_2
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doStudent
 * Signature: ([Lcom/guoqiang/androidjni/Student;)[Lcom/guoqiang/androidjni/Student;
 */
JNIEXPORT jobjectArray JNICALL Java_com_guoqiang_androidjni_JniUtils_doStudent___3Lcom_guoqiang_androidjni_Student_2
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_guoqiang_androidjni_JniUtils
 * Method:    doAll
 * Signature: ([I[Ljava/lang/String;[Lcom/guoqiang/androidjni/Student;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_guoqiang_androidjni_JniUtils_doAll
  (JNIEnv *, jclass, jintArray, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
